#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_USERNAME --password-stdin
echo "$HEROKU_TOKEN" | docker login --username=_ --password-stdin registry.heroku.com
docker ps -a
docker images
docker rmi --force registry.heroku.com/shreesharaj/katte:frontend registry.heroku.com/shreesharaj/katte:backend registry.heroku.com/shreesharaj/katte:prod 