#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker ps -a
docker images
docker push shreesharaj/katte:frontend
docker push shreesharaj/katte:backend
docker push shreesharaj/katte:proxy