#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_USERNAME --password-stdin
echo "$HEROKU_TOKEN" | docker login --username=_ --password-stdin registry.heroku.com
docker ps -a
docker images
docker push registry.heroku.com/shreesharaj/katte:frontend
docker push registry.heroku.com/shreesharaj/katte:backend
#docker push registry.heroku.com/shreesharaj/katte:prod